---
title: "Project - Analysis of housing price of Korea"
author: "Jae Hyun Lee, jl914"
date: "3/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(lubridate)
library(grid)
library(gridExtra)
set.seed(642)
```

```{r,include=FALSE}
#apartment <- read_csv("Seoul.csv")
apartment <- read_csv("gangnam.csv")
apartment <- apartment %>% 
  mutate_if(is.character,as.factor) %>% 
  dplyr::select(-city,-name, -road_name, -district,-district1,-district2,-day, -addr) %>% 
  mutate(price = price/100, date = as_date(str_c(month,"01")), age = year(date)-built) %>% 
  mutate(lprice = log(price), lsize = log(size), lfloor = log(floor), lage = log(age+2), lpark = log(park)) %>% 
  arrange(date,lprice)
idx <- apply(apartment,1,function(x){sum(is.na(x))})#is.na(apartment$lage)
apartment <- apartment[idx==0,]
test <- read_csv("test.csv")
test <- test %>% 
  mutate_if(is.character,as.factor) %>% 
  dplyr::select(-city,-name, -road_name, -district,-district1,-district2,-day, -addr) %>% 
  mutate(price = price/100, date = as_date(str_c(month,"01")), age = year(date)-built) %>% 
  mutate(lprice = log(price), lsize = log(size), lfloor = log(floor), lage = log(age+2), lpark = log(park)) %>% 
  arrange(date,lprice)
idx <- is.na(test$lfloor)
test <- test[!idx,]
```

```{r}
library(ggthemr)
m_price <- apartment %>% 
  group_by(date) %>% 
  summarise(price = mean(price))

myplot <- ggplot() +
  geom_line(data = m_price, mapping = aes(x = date, y = price)) +
  labs(title = "average price of apartment in Korea") +
  ggthemes::theme_tufte()

beta <- Tbeta(data,predictors)$beta
beta <- as.data.frame(beta) %>% 
  `colnames<-`(c(paste0("beta",1:8)))
ti <- m_price$date
plot_list <- list()
beta[,1]
for(i in 1:8){
  plot_list[[i]] <- ggplot(data = beta)+
    geom_line(mapping = aes(x = ti, y = beta[,i])) +
    labs(title = paste("coefficient of beta",i))
}
plot_list[[1]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta1)) +
  labs(title = "coefficient of intercept") +
  ggthemes::theme_tufte()
plot_list[[2]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta2)) +
  labs(title = "coefficient of Size") +
  ggthemes::theme_tufte()
plot_list[[3]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta3)) +
  labs(title = "coefficient of Floor") +
  ggthemes::theme_tufte()
plot_list[[4]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta4)) +
  labs(title = "coefficient of Age")+
  ggthemes::theme_tufte()

plot_list2 <- list()
plot_list2[[1]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta5)) +
  labs(title = "coefficient of lpark") +
  ggthemes::theme_tufte()
plot_list2[[2]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta6)) +
  labs(title = "coefficient of convenie") +
  ggthemes::theme_tufte()
plot_list2[[3]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta7)) +
  labs(title = "coefficient of edu") +
  ggthemes::theme_tufte()
plot_list2[[4]] <- ggplot(data = beta) +
  geom_line(mapping = aes(x = ti, y = beta8)) +
  labs(title = "coefficient of subway")+
  ggthemes::theme_tufte()

grid.arrange(grobs = plot_list,nrow = 2)
grid.arrange(grobs = plot_list2, nrow = 2)
```

```{r predictor selection}
set.seed(642)
data <- apartment %>% 
  dplyr::select(lprice,lsize,lfloor,lage,lpark,convenie,edu,subway,date)
#data <- apartment %>% 
#  dplyr::select(lprice,lage,lfloor,lsize,date)
cor(data[,-9])
pred_mat <- model.matrix(lm(lprice ~., data = data[,-9]))
cormat <- pred_mat %>% as.matrix %>% cor(use = "na.or.complete")
# Heatmap plot
reshape2::melt(cormat) %>% ggplot(., aes(Var1, Var2)) + geom_tile(aes(fill = value)) +
  scale_fill_distiller(direction=1, palette = "RdBu", limits = c(-1,1), na.value = "white") +
  theme(axis.text.x = element_text(size=10, angle=90),
        axis.text.y = element_text(size=10),
        axis.ticks = element_blank()
        ) +
  xlab("Variables") +
  ylab("Variables")
```

```{r}
data <- apartment %>% 
  dplyr::select(lprice,lsize,lfloor,lage,lpark,convenie,edu,subway,date)
predictors  <- c("lsize","lage","lfloor","lpark","subway","edu","convenie")
candidate <- list()
performance <- list()
num <- 0
for(i in 1:7){
  candidate[[i]] <- combn(predictors,i)
}

for(i in 1:7){
  for(j in 1:ncol(candidate[[i]])){
    num <- num+1
    predictor <- candidate[[i]][,j]
    beta <- Tbeta(data,predictors = predictor)$beta
    m0 <- apply(beta,2,mean)#m0 <- c(1,rep(0,ncol(beta)-1));
    C0 <- diag(diag(cov(beta)),nrow = ncol(beta))
    n0 <- 100; S0 <- 0.3^2
    T <- dim(beta)[1]
    q <- dim(beta)[2]
    nmc = 5000
    form <- as.formula(paste("lprice",paste0(predictors,collapse = "+"),sep = "~"))
    K = length(unique(test$date))
    model <- lmvar(data = data, predictors = predictor, p=1, del = del, m0 = m0, C0 = C0, n0 = n0, S0 = S0)
    fore <- forecast(data = data, predictors = predictor, p=1, K = K, G = model$G, del = del, const = model$const,
                  mT = model$m[,T], CT = model$C[,,T], nT = model$n[T], ST = model$S[T], nmc = nmc)
    aics <- aic(model$e,q)
    beta3 <- apply(fore$beta,c(1,2),mean)
    err <- MSE(test,predictor,beta3)$err
    pMSE <- apply(err, 2, function(x){mean(x^2)})
    performance[[num]] <- list("aic" = aics,"mse" = pMSE,"pred" = paste(predictor,collapse = "+"))
    print(num)
  }
}
result <- bind_rows(performance)
result <- result %>% 
  arrange(aic,mse)
candidate <- head(result,20)
```


```{r}
cor(beta)
```

```{r model comparison}
#predictors <- c("lsize","lage","lfloor","lpark","subway","edu","convenie")
#predictors <- c("lsize","lage","lfloor")
predictors <- c("lsize","lpark","subway","edu")
beta <- Tbeta(data,predictors)$beta
del <- c(0.90,0.90)
m0 <- c(1,1,0,0,0); C0 <- diag(diag(cov(beta)),nrow = ncol(beta));
n0 <- 100; S0 <- 0.3^2
T <- dim(beta)[1]
q <- dim(beta)[2]
nmc = 5000
K = length(unique(test$date))
form <- as.formula(paste("lprice",paste0(predictors,collapse = "+"),sep = "~"))


model1 <- lmr(data = data, predictors = predictors)
n <- nrow(data)
X <- as.matrix(cbind(rep(1,nrow(data)),data[,predictors]))
S <- model1$S
m <- model1$m; C <- S*solve(t(X)%*%X)
fore1 <- list(beta = array(t(MASS::mvrnorm(n = K*nmc,mu = m, Sigma = C)),dim = c(q,K,nmc)),
              v = matrix(1/rgamma(K*nmc, n/2, n*S/2),nrow = K))

model2 <- lmvr(data = data, predictors = predictors, del = del, m0, C0, n0, S0)
fore2 <- forecast(data = data, predictors = predictors, p=1, K = K, G = diag(rep(1,q),nrow = q),del = del,
                  mT = model2$m[,T], CT = model2$C[,,T], nT = model2$n[T], ST = model2$S[T], nmc = nmc)

model3 <- lmvar(data = data, predictors = predictors, p=1, del = del, m0 = m0, C0 = C0, n0 = n0, S0 = S0)
fore3 <- forecast(data = data, predictors = predictors, p=1, K = K, G = model3$G, del = del, const = model3$const,
                  mT = model3$m[,T], CT = model3$C[,,T], nT = model3$n[T], ST = model3$S[T], nmc = nmc)

#comparison by RMSE, prediction accuracy, coverage, AIC
#model deviance
aics <- c(aic(model1$e,4), aic(model2$e,4), aic(model3$e,4))
#model prediction accuracy by RMSE
beta1 <- matrix(rep(model1$m,3),ncol = 3)
beta2 <- apply(fore2$beta,c(1,2),mean)
beta3 <- apply(fore3$beta,c(1,2),mean)
#point prediction
est <- cbind(MSE(test,predictors,beta1)$pred,MSE(test,predictors,beta2)$pred,MSE(test,predictors,beta3)$pred)
err <- cbind(MSE(test,predictors,beta1)$err,MSE(test,predictors,beta2)$err,MSE(test,predictors,beta3)$err)
pMSE <- apply(err, 2, function(x){mean(x^2)})
#Coverage
y_int1 <- interval(test,predictors, beta = fore1$beta, S = fore1$v)
y_int2 <- interval(test,predictors, beta = fore2$beta, S = fore2$v)
y_int3 <- interval(test,predictors, beta = fore3$beta, S = fore3$v)
coverage1 <- coverage(test$lprice, y_int1)
coverage2 <- coverage(test$lprice, y_int2)
coverage3 <- coverage(test$lprice, y_int3)

#marginal likelihood
ggplot()+
  geom_line(mapping = aes(x = ti, y = model1$mlik),color = "blue") +
  geom_line(mapping = aes(x = ti, y = model2$mlik),color = "red") +
  geom_line(mapping = aes(x = ti, y = model3$mlik),color = "yellow")
m1 <- cumsum(log(model1$mlik+1e-18))
m2 <- cumsum(log(model2$mlik+1e-18))
m3 <- cumsum(log(model3$mlik+1e-18))
llik <- rbind(m1,m2,m3)
prob <- exp(apply(llik,2,function(x){x - max(x)})); prob <- prob/apply(prob,2,sum)
ggplot()+
  geom_line(mapping = aes(x = ti, y = m1),color = "blue") +
  geom_line(mapping = aes(x = ti, y = m2),color = "red") +
  geom_line(mapping = aes(x = ti, y = m3),color = "yellow")
ggplot()+
  geom_line(mapping = aes(x = ti, y = prob[1,]),color = "blue") +
  geom_line(mapping = aes(x = ti, y = prob[2,]),color = "red") +
  geom_line(mapping = aes(x = ti, y = prob[3,]),color = "yellow")
```


```{r}
df_plot1 <- data.frame(lprice = test$lprice, 
                      pred = MSE(test,predictors,beta1)$pred,
                      lwr = y_int1[,1],upr = y_int1[,2]) %>% arrange(pred)
df.test <- data.frame(college = linear.test.norm$college,
Apps = exp(linear.test.norm$Apps),
pred = exp(predict(glm.norm.2, linear.test.norm, type = "response")),
lwr = bound.test.norm[,1], upr = bound.test.norm[,2]) %>%
arrange(pred)
19
ggplot(df.norm, aes(x = pred, y = Apps)) +
geom_ribbon(aes(ymin = lwr, ymax = upr),
fill = "skyblue", alpha = 0.5) +
geom_point() +
#geom_text() +
annotate("text", x = c(15000,25000), y = c(45000,6000), label = c("Rutgers", "Brigham Young")) +
labs(x = "Predicted application", y = "Application",
title = "95% Prediction Intervals under the linear model")
```

